### ISSUE TITLE
Google location API fails on Heroku site

### ISSUE THREAD

**Issue by mmerkes** [ionic-in-action/chapter6#1]
If you go to the Heroku site for this page, the Google location API fails to go through with the following error:

Mixed Content: The page at 'https://ionic-in-action-chapter6.herokuapp.com/#/search' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://maps.googleapis.com/maps/api/geocode/json?address=Seattle,+WA'. This request has been blocked; the content must be served over HTTPS.

**Comment by gnomeontherun** [comment]
Fixed on demo site. Thanks!
