### ISSUE TITLE
Settings in chapter6

### ISSUE THREAD

**Issue by hrolf** [ionic-in-action/chapter6#3]
If you change settings from Fahrenheit to Celsius the current conditions , after pushing a favorite,  still present the temp in Fahrenheit. Seems that no new data is loded.

**Comment by hrolf** [comment]
I now fixed it by changing weather.js with:
 $scope.$on('$ionicView.enter', function() {
    $http.get('/api/forecast/' + $stateParams.lat + ',' + $stateParams.lng, {params: {units: Settings.units}}).success(function (forecast) {
    $scope.forecast = forecast;
  });
});
Regards
Rolf

**Comment by gnomeontherun** [comment]
Rolf, that is a good catch and is correct due to the way that Ionic caches a view by default. The problem is this view gets cached, and doesn't reload the data. Your fix is a good way to handle it.
