### ISSUE TITLE
Don´t work in mobile

### ISSUE THREAD

**Issue by hrolf** [ionic-in-action/chapter6#4]
Works well in PC but transferred to an mobile via ionic view or as akp it cannot show the current conditions. Why?

**Comment by gnomeontherun** [comment]
Are you able to run in a debug mode to see any logs that might be provided?

**Comment by hrolf** [comment]
It worked alright in "ionic serve" but it did not fetch data in the mobile.
Instead of the proxy address I also put in the direct address in weather.js.
Then it worked in the mobile but not in " ionic serve".
When then having console.log after .success I got :  _No
'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:8100' is therefore not allowed *
*access._

_/Rolf_

2016-10-01 19:55 GMT+02:00 Jeremy Wilken notifications@github.com:

**Comment by gnomeontherun** [comment]
That is a CORS issue, which is related to the way the API works. Read more here http://blog.ionic.io/handling-cors-issues-in-ionic/.

**Comment by hrolf** [comment]
Now I understand, thank you!

söndag 2 oktober 2016 skrev Jeremy Wilken notifications@github.com:

**Comment by hrolf** [comment]
I don´t know if this is the same problem but the wind arrow don´t rotate in
the moile but rotate ok when using "ionic serve".
By the way the arrow shall be down not up (with the wind)

2016-10-02 5:19 GMT+02:00 Jeremy Wilken notifications@github.com:

**Comment by linh626688** [comment]
my app receive data on browser but , when i build apk file and test app on my device it can't search data, i think the app miss permission connect Internet in my device (Android).  Help me
