### ISSUE TITLE
how to deploy heroku  avoiding cors error

### ISSUE THREAD

**Issue by hiscc** [ionic-in-action/chapter6#6]
hey man, the book is useful.
however when i deploy this project to heroku , it's not work, because of cors.
how did  you reslove this problem? thx ;)
my [serve.js](https://github.com/ManInBoat/weather/blob/master/serve.js)  
````
var express = require('express');

var app = express();
app.use(express.static('www'));
app.set('port', process.env.PORT || 5000);

app.listen(app.get('port'), function () {
  console.log(app.get('port'));
});
````

my [package.json](https://github.com/ManInBoat/weather/blob/master/package.json)
````
  "engines": {
    "node": "6.6.0"
  },

  "scripts": {
    "start": "npm run nodeserver&& npm run ionicserver",
    "ionicserver": "ionic serve",
    "nodeserver": "node serve.js"
  }
````

**Comment by gnomeontherun** [comment]
What does your Procfile contain? You don't need to run both ionic serve and the express server you just want to have the files build using ionic.

**Comment by hiscc** [comment]
ok, i run ``ionic serve`` in my pc , it's work,
when i deploy heroku, i need express,so i bootstarp it by ``node serve.js``
the problem is that when i deploy heroku i don't know how to make it work on heroku  .
i saw the [live demo](http://ionic-in-action-chapter6.herokuapp.com/)  that you deployed heroku,it's work well, how  do you deploy heroku with nodejs? can you show me some nodejs code .
thx for your reply ;)

**Comment by gnomeontherun** [comment]
Try looking at this example, it has a more complex server than you need but its a good point of reference. The Profile is what Heroku uses to run the server.

https://github.com/driftyco/ionic-themer
