### ISSUE TITLE
Cross domain problem

### ISSUE THREAD

**Issue by ShenXinKang** [ionic-in-action/chapter6#7]
I git the whole chapter6 project and try it.
I search a location and get the results. But when I click one for detail.
**An error happen:**
GET http://localhost/api/forecast/42.5475383,-71.2785583?units=us 404 (Not Found)

With this error,I can't get data form Froecast.io

**Comment by gnomeontherun** [comment]
Looks like they changed the URL for the API. I updated the `ionic.project` file in this repo, update it and it should work again.

https://github.com/ionic-in-action/chapter6/blob/master/ionic.project

**Comment by 610716076** [comment]
I found an intersting thing about this problem.
When I run this project with IDE or http-server,it will cause this problem.
But when I run this project with “ionic serve” in CLI. It's OK.

But I don't know what make differences.

**Comment by ShenXinKang** [comment]
I found an intersting thing about this problem.
When I run this project with IDE or http-server,it will cause this problem.
But when I run this project with “ionic serve” in CLI. It's OK.

But I don't know what make differences.

**Comment by gnomeontherun** [comment]
The problem is that you need a CORS proxy which the Ionic CLI provides. It should be mentioned in the chapter. 

Jeremy

**Comment by ShenXinKang** [comment]
THX,I find it in the book.
